### ISSUE TITLE
Error in Line no 7 of the code

### ISSUE THREAD

**Issue by bipeensinha** [bipeensinha/uberaz400#1]
@mukundmckinsey  please check code @abhishikth-yagalla Please support mukund @jyotishaz400 Take ownership @sudhanshumca  send me the update

**Comment by abhishikth-yagalla** [comment]
Working on the code @bipeensinha

**Comment by sudhanshumca** [comment]
please provide update ;)

**Comment by jyotishaz400** [comment]
code looks perfect

**Comment by bipeensinha** [comment]
![download](https://user-images.githubusercontent.com/49720823/153847018-a6dee663-c7f5-4701-b1e0-63126ed704d0.jpg)

**Comment by bipeensinha** [comment]
Thank you issues closed
